name: RunForMoney
main: pawarenessc\RFM\Main
version: 11.2.3
api: [4.0.0,3.0.0,3.5.0]
authors: [PawarenessC,NRedFire]
load: POSTWORLD
description: play tag.
commands:
 setupui:
  description: "逃走中の制御コマンド"
  usage: "/setupui"
 tagui:
  description: "逃走中"
  usage: "/tagui"
 tagshop:
  description: "逃走中のショップです"
  usage: "/tagshop"
